### ISSUE TITLE
Do not show download buttons for datasets that are not loaded

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#100]
A small fraction of papers are still being processed. They have datasets but data has not been loaded yet. We should disable the "Add" and other download buttons for these datasets. The easiest way to do it is:

`disabled = "" if dataset.has_data_in_db() else "disabled"`

The `has_data_in_db()` method already exists in the Dataset model.

**Comment by vsoch** [comment]
Sounds good! Let's make sure to merge / work on the gene refactor first, because it is becoming increasingly harder to combine with current master.

**Comment by vsoch** [comment]
okay, I've added this to both the server rendered table and browser side, will come in future PR.

**Comment by abarysh** [comment]
Tested in PR #116 -- fixed!
