### ISSUE TITLE
Wrong number of datasets displayed on papers detail page

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#101]
Example: on /papers/289/ each page of the datasets table shows 11 datasets (instead of 10, as it should be). The last dataset on page 1 is the first dataset on page 2 (so there's overlap between pages).

**Comment by vsoch** [comment]
This was an indexing off by one error, I've fixed this and will add to PR soon.

**Comment by abarysh** [comment]
Tested in PR #116 -- fixed!
