### ISSUE TITLE
Switch join_and_more functions to a different delimiter

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#103]
In a few places where we use STRING_AGG to aggregate related fields by ",", we also apply `split` and `join_and_more` to display a truncated subset of the fields. Unfortunately, some of the fields have "," inside them (e.g., certain condition names such as "3-amino-1,2,4-triazole"). As a result, they are displayed as "3-amino-1, 2, 4-triazole" which looks weird and is incorrect.
I suggest we switch STRING_AGG and "join_and_more" to a different delimiter. E.g., "; "?

**Comment by vsoch** [comment]
It looks like ; would work, I don't see it present in any phenotypes names, or authors first/last names.

**Comment by abarysh** [comment]
Sounds good, let's go with ";"

**Comment by abarysh** [comment]
Tested on PR #116 (after 2nd commit) -- fixed!
