### ISSUE TITLE
After searching, domain name not preserved

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#106]
Weird bug:

If I go to https://yeastphenome.org/datasets/ and search for "growth", the URL in the browser switches to https://calico-yeast-phenome-01.uc.r.appspot.com/datasets/?query=growth (instead of https://yeastphenome.org/datasets/?query=growth).

**Comment by vsoch** [comment]
Ah, I think this is because the domain name is a variable - I'll swtich it to use yeastphenome for production from now on.

**Comment by vsoch** [comment]
This should now be fixed.

**Comment by abarysh** [comment]
Yep, tested on production -- fixed!
