### ISSUE TITLE
Ajax error after sorting datasets results table

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#107]
Hard to track down the exact cause of the error, but here's a way to reproduce it.

After I search "growth" at /datasets/, I end up at https://calico-yeast-phenome-01.uc.r.appspot.com/datasets/?query=growth. I then sort by "Medium" (all good) and move to page 5 (all good). If I try to move to pages 2, 3 or 4, I get this error:

`DataTables warning: table id=papersTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Comment by vsoch** [comment]
I just tried to reproduce this (and couldn't) so I think it might have been related to #101. I'll PR with the fix and you can test again!

**Comment by abarysh** [comment]
Tested in PR #116 -- fixed!
