### ISSUE TITLE
Add scatter plots to gene-gene and dataset-dataset similarity tables

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#108]
The idea is to provide evidence for the correlation coefficient that we report for gene-gene pairs and dataset-dataset pairs. Ideally it would be something like this:
- in the all gene-gene similarity tables (the preview ones on the Gene detail page and the long ones on the /gene/XXX/similar/ page), we add one additional column with a link to "Scatter plot".
- when you click on the link, you're taken to a new page (located at /genes/XXX/similar/scatterplot/) that contains an interactive scatter plot of phenotypic scores for gene1 and gene2. Interactive here means that the user can hover over each dot and see the name of the dataset that corresponds to that dot.

Same thing for dataset-dataset pairs.

**Comment by vsoch** [comment]
So if we are comparing gene1 and gene2 across all datasets, wouldn't gene2 need to also be represented in the URL?

**Comment by abarysh** [comment]
Yep, you're right, both genes should be in the URL.
