### ISSUE TITLE
Make a custom 404 page

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#110]
This would be the page where the users end up if they follow an old (currently not existent) or a wrong link. It should have some kind of high-level website map to help the user orient themselves and figure out what they were actually looking for.

**Comment by abarysh** [comment]
Testing on staging -- it look good, but we need to make it more obvious that:
a) you're on www.yeastphenome.org
b) this is a 404 Page Not Found

I don't have a super-clear idea of how to do it yet. But probably putting "404 Page Not Found" as a title and "YeastPhenome.org" as a subtitle. Under that I would put something like "Sorry, the page you're looking for cannot be found."

Then the links should be:
- Home Page
- About Yeast Phenome
- Explore Data
   - Papers
   - Datasets
   - ... (all other sections)

**Comment by vsoch** [comment]
it's not very good, but it does have all the items listed above! https://staging-dot-calico-yeast-phenome-01.uc.r.appspot.com/404

![image](https://user-images.githubusercontent.com/814322/102647990-f2513080-4123-11eb-84e6-82e0e494c80c.png)

I probably should have brought in bootstrap to do nicer spacing. Let me know if it's okay, or if you want it redone.

**Comment by abarysh** [comment]
I think it's ok to merge this as is, but we should keep the issue open until we're 100% happy with the page. I would be happy if we moved all the text to the right of the image (i.e., a 2 column layout -- image on the left, text on the right). We can do it now or later, up to you.

**Comment by vsoch** [comment]
It's pretty ugly, I'm going to give a shot to at least have two columns!

**Comment by vsoch** [comment]
okay, slightly less offensive? 

![image](https://user-images.githubusercontent.com/814322/102653957-fafa3480-412c-11eb-877e-b927576d715d.png)

**Comment by abarysh** [comment]
Yeah, much better! Just make sure that the link are underlined to make it clear they are links (as opposed to simple text).

PS: the image is copyright-free, right? :) don't want to get in trouble about art licenses.

**Comment by vsoch** [comment]
Yeah, it's from drawkit! https://www.drawkit.io/license

**Comment by vsoch** [comment]
okay underlines are added

![image](https://user-images.githubusercontent.com/814322/102654926-a5268c00-412e-11eb-93f4-8907f0b056ef.png)

I think this was the last issue, so I'll push updates, and then merge to master and deploy to production.

**Comment by vsoch** [comment]
This should be good for now, we can open another issue if there is some request to change or improve it.
