### ISSUE TITLE
Integrate scores (and similarities) table with the corresponding histrogram

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#112]
I see an opportunity for simplifying the user's interaction with the /genes/XXX/scores/ and /genes/XXX/similar/ pages (and same for datasets).

Ideally, we could get rid of the "Search genes" box if we were able to use the "Filter" feature of the table to find the right gene, and the click (on either the row itself or on a special link) to highlight that gene's position on the histogram (i.e., the right bar in the graph).

**Comment by vsoch** [comment]
Done with #134
