### ISSUE TITLE
Figure out how to enable users to select very short bars in the histogram

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#113]
Problem: the most interesting bars in a /genes/XXX/scores/ and /genes/XXX/similar/ histograms (and the same for datasets) are the shortest ones (the extremes on the left and right). And the user cannot select them directly to see what datasets (or genes) are in that bin.

There might be several solutions. A potentially easy one could be to enable switching between linear and log scales on the y-axis. Once the user switches to the log scale, the short bars might be high enough to click on them.

**Comment by vsoch** [comment]
Done with #134. Note the references to views for genes should be datasets, we will add corresponding genes views and track progress via issue #63.
