### ISSUE TITLE
Removing a dataset from the cart directly in the cart page doesn't remove the dataset 

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#115]
If you have a set of datasets in the cart and you remove one before clicking "Download", that dataset will still be present in the downloaded file.

**Comment by vsoch** [comment]
ack, I definitely thought of this and tried to account for this by making the dataset ids derived from the session, but it must be that the session can't be updated from the current page.

**Comment by vsoch** [comment]
Fixed in #127.
