### ISSUE TITLE
bug with download cart space

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#128]
Given a few challenges with the "Add dataset to Download Cart" buttons, I am glad we have an opportunity to think about the Download feature as a whole. 

Currently, there're 4 ways to download data:
1. Download immediately the data you're looking at (for any given dataset or a gene)
2. Download immediately the data for all datasets in a table [not always available: yes at /phenotypes/587/; no at /conditions/4/]
3. Add a specific dataset to the Download Cart
4. Add all datasets in a table to the Download Cart [not always available: yes at /conditions/4/; no at /papers/289/]

[Option 5 will be available later on -- download all the data in the database in a single file.]

I think the order in which I listed the options also corresponds to their relative importance: option 1 is essential, 2 is important, 3 is nice to have and 4 is the cherry on top.

We can live perfectly fine with options 1 and 2 only, but options 3 and 4 (the download cart) are really useful and it would be great to keep them. However, we have to make sure they work robustly and consistently throughout the website.

My thoughts:
- if you feel that your current implementation (jquery) is not appropriate for our case, let's use a different one (e.g., react). I think it's worth the investment because patching an imperfect implementation wastes time in the long term.
- I think that we should keep the functionality as familiar for the user as possible. Adding something to the cart should be a 1-click action (using checkboxes and an "add all to cart" button would be 2 clicks).
- we currently have an inconsistency -- the cart only takes datasets, not genes. That's something to consider -- is there a relatively simple solution?
- minor point (probably captured by another issue): all dataset tables should have the same buttons (e.g., see option 2 example above) and these buttons should have the same name (e.g., /conditions/4/ says "Add all datasets to Downloads" whereas /phenotypes/587/ says "Add All to Download Later"). The buttons should just be part of the html template that has the datasets table.

**Comment by vsoch** [comment]
Checkboxes could actually be an improvement - right now we require N clicks for N objects, but with a "select all" at the top, it would only be two clicks to select all datasets and then add/remove them. The user could even select all then remove a few, which would still be fewer clicks.

I'm not hugely experienced in Vue.js or React beyond little toy projects, and I think it would add complexity and inconsistency with respect to our front end strategy. Working with another template rendering framework alongside Django's native one also means it will require a bunch of `{% raw %}{% endraw %}` to further complicate things.

So I'd like to try checkboxes, if it's okay with you.

**Comment by vsoch** [comment]
I also don't fully understand what happens when the session is changed on the backend, but not on the front end (and then still manipulated) which might have led to a bug in the view cart view, and could be relevant here. If we cleanly refresh the page we don't have this issue!

**Comment by abarysh** [comment]
Re: number of clicks -- it kinda depends on the use case. To add 1 dataset is 2 clicks; to add all of them -- also 2 clicks; to add some of them -- more than 2 but less than N. Will this work ok with pagination? I.e., would the user need to click "Add selected" before moving to the next page?

**Comment by abarysh** [comment]
And, once added, how would I remove the dataset from cart? E.g., I accidentally clicked on the wrong row and want to remove a dataset from the cart? Do I need to go to the cart page? If I understand you correctly, on the cart page the interface won't change and we'll still have the "Remove" buttons next to each dataset?

**Comment by vsoch** [comment]
> Re: number of clicks -- it kinda depends on the use case. To add 1 dataset is 2 clicks; to add all of them -- also 2 clicks; to add some of them -- more than 2 but less than N. Will this work ok with pagination? I.e., would the user need to click "Add selected" before moving to the next page?

It would be limited to the current page.

> And, once added, how would I remove the dataset from cart? E.g., I accidentally clicked on the wrong row and want to remove a dataset from the cart? Do I need to go to the cart page? If I understand you correctly, on the cart page the interface won't change and we'll still have the "Remove" buttons next to each dataset?

The same way, selecting a bunch or subset and clicking on "Remove from cart."

**Comment by abarysh** [comment]
Yeah, somehow it doesn't seem to be a great solution to me -- we're complicating the UI (with multiple clicks) to solve a back-end problem.

And if you think about it -- we are adding clicks in every possible case:
- Adding/removing 1 dataset: currently -- 1 click, future -- 2 clicks
- Adding all datasets: currently -- 1 click (wherever we have a button "Add all.." and we should have it everywhere), future -- 2 clicks
- Adding/removing some datasets: currently -- either add 1 by 1 or click "Add all.." and remove what's needed; future -- the same but with 1 extra click at each step.

Are you sure you don't want to sleep on it and see if we can figure out what's the issue with our current UI implementation? I sounds to me that all we're doing is updating a list of numbers in a cookie. We just need to streamline the process of adding/removing numbers from that list. Am I misunderstanding it?

**Comment by vsoch** [comment]
The current version seems to consistently work fine until 40 something - I'm on my other computer now and stopped at 49 (the add button is grayed out). It could just be that there is some error message we can't see since the result isn't rendered to the page. I wish I had more insight to the why (and then what we need to do to fix it) but (at least right now) I don't.

**Comment by abarysh** [comment]
Yep, makes sense. I suggest we keep thinking about it. I'm sure there's a way to debug it. I wanted to test it locally myself but the latest pull from the master was giving me an error about missing  graph models -- is that fixed now? if yes, I can pull again and see what i can see.

**Comment by vsoch** [comment]
It should be! I had forgotten to add a graphs.py under the papers module, but it should be there now.

**Comment by abarysh** [comment]
Cool, I'll check it out now

**Comment by abarysh** [comment]
Ok, so here're my thoughts:
- It was fairly hard to reproduce the error locally (I couldn't get the buttons to freeze, but eventually caught one case). The bug is fairly stochastic.
- When I got the bug, the Chrome Javascript Console had the following error: net::ERR_CONNECTION_REFUSED for the /cart/add/XXX/ 
- I assumed this was the connection to the database and wondered why are we connecting to the database at this stage (we're just updating a list of dataset ids, right?). This was also consistent with the fact adding a dataset to cart should be instantaneous (again, no database hits) but the operation was obviously slower locally than on the staging server (as all database queries are, as expected). 
- I looked into this and saw that in `add_to_cart` function (line 289 in /common/views.py) you have `datasets = Dataset.objects.filter(id__in=dataset_id.split(","))`. This shouldn't be needed, right? I looked at `add_bulk_datasets` as well and saw that you don't use or need any information about datasets other than their ids which you already have.

So I would suggest to eliminate all database queries from the cart function (not sure if I found the only one or there're more) up until the user visits the Cart itself.

**Comment by vsoch** [comment]
Oh! I just realized... the add and remove cart functions are rate limited! It could be that - the production limit is 50 and development higher, and after exceeding you’d see that error. Try removing those decorators https://github.com/yeastphenome/yeastphenome.org/blob/86630f956e7807798d480d254eae942d0b9a168b/yeastphenome/apps/common/views.py#L277.

**Comment by abarysh** [comment]
I see how that could help avoiding the problem on production, but are you saying I should try removing them in development too? Could you elaborate on what this will do in development?

**Comment by vsoch** [comment]
I would delete the line entirely, or set the limit to something like 5000 just for those views (which would then be active for development and production). It’s very likely that a person could use those views a few hundred times in a day if they are downloading a lot. It will (possibly) avoid the connection refused error. If we are still seeing it, then we’ll need to look further into how Django handles (and possibly blocks) bulk requests.

And definitely if we don’t need the database query we can remove it!

**Comment by abarysh** [comment]
Yes, that is it. It was already set to 5000/1d in development (50/1d in production). I changed it to 10/1d for development and was able to perfectly reproduce the button freeze after 10 datasets added. It's not a connection error though, it's a "403 (Forbidden) error" plus a "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 1". But it doesn't matter, now we know what the problem is.

Can I leave it to you to fix it? I do still think that we should remove the database queries. They're not necessary and will speed up the whole thing.

**Comment by vsoch** [comment]
Woohoo! Super great teamwork, I never would have thought of it if you hadn’t mentioned the error message just now!

Yes, I’ll fix it first thing tomorrow, and see if I can remove the database query there too.

**Comment by abarysh** [comment]
Cool! Great work! 👍🏻

**Comment by vsoch** [comment]
This discussion about download strategy has moved into issue #102, and this issue is scoped to be about the broken download cart (which will be fixed with an upcoming PR). I think we were thinking of changing the download strategy because of this bug, but now we don't need to (and can focus on button names, functionality in #102.)
