### ISSUE TITLE
Model for Similarity Calculation

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#18]
@abarysh I wanted to briefly discuss the model for the DatasetSimilarity, if we want to have some kind of nice heatmap to show differences in a subset of datasets we could use these scores! Here is what I have in mind:

```python
class DatasetSimilarity(models.Model):
    """A dataset similarity is a similarity metric calculated to compare genes
       in two datasets
    """
    dataset1 = models.ForeignKey(Dataset, on_delete=models.DO_NOTHING)
    dataset2 = models.ForeignKey(Dataset, on_delete=models.DO_NOTHING)
    metric = models.CharField(max_length=50)
    score = models.DecimalField(max_digits=10, decimal_places=3)
```
and then on addition of a new dataset it would trigger an operation to calculate new scores. Depending on how long that takes (if more than a trivial amount of time) we might need to think about how to add asyc-type tasks. I can also hold off on adding this now if you want to discuss in more detail and add at a later time!

**Comment by abarysh** [comment]
Yes, absolutely, I think this makes sense. (Minor point -- should the on_delete be CASCADE? If a dataset gets removed, it only make sense to delete all of its similarities).

Orthogonally, we should consider adding a GeneSimilarity model with a similar structure:

```python
class GeneSimilarity(models.Model):
    gene1 = models.ForeignKey(Gene, on_delete=models.CASCADE)
    gene2 = models.ForeignKey(Gene, on_delete=models.CASCADE)
    metric = models.CharField(max_length=50)
    score = models.DecimalField(max_digits=10, decimal_places=3)
```

Neither DatasetSimilarity nor GeneSimilarity need be updated instantly. We can schedule regular computations (e.g., once a week). Updating GeneSimilarity in particular will be a bit more complex because the entire table will need to be re-populated: adding a new Dataset will change all GeneSimilarity scores, even if not by much.

**Comment by vsoch** [comment]
+1 for `models.CASCADE` and cool idea for the `GeneSimiliary` too! I'll implement first the `DatasetSimilarity` and figure out how to do the scheduled job, and when we have a strategy for that it will be easier to add the `GeneSimilarity` to do the same.

**Comment by abarysh** [comment]
Sounds good. Computing similarities between all pairs of ~16,000 datasets or ~6,000 genes is not trivial. Over time, we've come up with a strategy (and the right implementations). So whenever you're ready, let me know, we can chat about how to maybe incorporate that code into the scheduled job.

**Comment by vsoch** [comment]
Oh great! I was actually just about to ask you about the metric of choice - I was reading about this one called [BayesGen](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2788366/) and then a paper with more expected testing (euclidean, pearson, etc.) https://academic.oup.com/bioinformatics/article/22/13/1616/193334. 

>  We conclude that combined similarity measures (and especially the EucPear measure), the Z-score-based Euclidean metric, the Pearson correlation measure and the local similarity measure perform better than the commonly used Euclidean metric. The Spearman rank correlation, that has not received much attention so far in studies of mRNA expression data, performs even better than these metrics and is a strong contender for the most effective one. A solid performer is the MD measure that significantly outperforms the other metrics on some datasets. Since it adjusts to the distribution of expression values in each experiment it is also less susceptible to chance similarities that are due to average or typical expression values. Another advantage of the MD measure is its flexibility, as it can produce good results even when the genes are co-expressed in an arbitrary subset of the experiments.

Methinks that we should probably chat about this sooner than later, I'd like to get this running soon so that I can work on some of the plots over the weekend. I'll send you a response in email (just seeing yours now!)

**Comment by vsoch** [comment]
We've added DatasetSimilarity and GeneSimilarity, so I think this issue can safely be closed.
