### ISSUE TITLE
pvalue should be in (non Python) scientific

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#24]
e.g., 1.6 x 10-4

See https://stackoverflow.com/questions/29260893/convert-to-scientific-notation-in-python-a-%C3%97-10b

**Comment by vsoch** [comment]
@abarysh are we okay with the current Decimal? If so, we can close this issue.

**Comment by abarysh** [comment]
Yes, we're good with Decimal.
