### ISSUE TITLE
Remove the up/down arrows (flippers?) in IntegerField widgets in admin

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#47]
With the update to Django3, all IntegerFields in admin are now represented with a widget that has up/down arrows for increasing/decreasing values 1 by 1. These arrows actually create more trouble for us, so I think we should remove them by assigning a TextInput widget to this field.

**Comment by vsoch** [comment]
I can test this today!

**Comment by vsoch** [comment]
Okay some notes for IntegerFields I found:

 - conditionType had two, chebi_id and pubmed_id, now changed to the TextInput widget
 - papers also had two, pmid and pub date, changed to be TextInput
 - there was a bug with displaying condition tags - we needed to query the list of conditions based on the type__name and not just the name, I fixed this.
 - collection -> ploidy
 - datasets -> tested_num

These are fixed, I'll have them in with the next PR hopefully sometime today. 

I also had the expectation that datasets admin views would be under datasets/admin.py, but they were actually in papers/admin.py. I think I must have forgotten to move them, so I created a new file to make it easier for the next person to be able to find them.

**Comment by abarysh** [comment]
Cool! For datasets/admin.py -- yeah, that's probably confusing for that to be displaced. There was an early reason for that (back when I was learning Django) but I think we can confidently re-work than now and move datasets back to datasets/admin.py. I can give it a try, if you like.

**Comment by vsoch** [comment]
Oh no need, I had already done it, will be part of a PR soon! :)
