### ISSUE TITLE
Add paper_datasets functionality to admin/paper/change

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#55]
As part of the data upload process, I need to be able to download the list of datasets for any given paper. So far, this functionality has been implemented in the public paper detail view (`paper_datasets` method in `/papers/views.py`) and executed by clicking to the "Download the list of datasets" link within the Datasets table displayed on the papers detail page (e.g., http://yeastphenome.org/papers/458/). 

I see that currently this functionality is present on the front end but is not working (error "Not Found. The requested resource was not found on this server"). Indeed, it would more sense to move this function to the admin site (it's not something that the user needs but the admin). 

Can we add this functionality as a link to the admin paper page, next to "Add another Dataset" link in the Datasets section (see screenshot attached)?
![Screen Shot 2020-11-09 at 12 03 38 PM](https://user-images.githubusercontent.com/11416566/98590555-d97f7080-2283-11eb-97bd-70a94c91eefb.png)

**Comment by vsoch** [comment]
I think so! I'll make some time to look later today!

**Comment by vsoch** [comment]
Closed with #56
