### ISSUE TITLE
Tagify allowing commas

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#66]
I've been playing around with the comma encoding issue this morning, and it appears that not having commas in the url isn't related to encoding them, but rather how tagify parses the tags (which correctly have them) to then pass on to do the search. The [instructions](https://yaireo.github.io/tagify/) seem fairly straight forward to change the delimiter, but this doesn't work in practice - it splits all the letters into single entities. Since the tagify fields are then passed to the server, we already have an issue since the whitelisted tag is automatically separated. I think the issue is that tagify expects us to use enforceWhitelist which we cannot do to allow random terms to be search.

I tried another possible solution, removing commas and doing a [replace](https://gist.github.com/simonw/30d2e626772e84edd688ba717a766c89) which would come down to annotating new fields without the commas before a search:

```python
    # Annotate models with comma removed values
    queryset = queryset.annotate(
        fixed_name=Func(
            F('name'),
            Value(','), Value(''),
            function='replace',
        )
    ).annotate(
        fixed_phenotype_name=Func(
            F('phenotype__name'),
            Value(','), Value(''),
            function='replace',
        )
    ).annotate(
        fixed_phenotype_measurement_name=Func(
            F('phenotype__measurement__name'),
            Value(','), Value(''),
            function='replace',
        )
    )
```
This seems to greatly increase the number of results, even for simple terms like "growth" - here we can see there is the same observable name, but many different conditionsets:

![image](https://user-images.githubusercontent.com/814322/100775821-01647e80-33c1-11eb-800a-457df8af8d7d.png)

@abarysh should I include this in a first round of changes to staging, or do you want me to restore / keep the original and you can have a try?

**Comment by abarysh** [comment]
Let's restore to the original and I'll give it a try (probably some time tonight).

**Comment by abarysh** [comment]
The delimiters are hardcoded in https://unpkg.com/@yaireo/tagify@3.17.7/dist/tagify.min.js (to be just "," as opposed to the settings in your template file). Would it make sense for us to download tagify.min.js, make the appropriate fix and to use our own "local" version (instead of linking the online version)?

**Comment by vsoch** [comment]
Hmm, I'm not sure that helps, the place where it's hard coded is the default, but it does take the user setting into account later in applySettings

```javascript
            applySettings: function (t, e) {
                this.DEFAULTS.templates = this.templates;
                var i = (this.settings = d({}, this.DEFAULTS, e));
                console.log(i);
                if (
                    ((i.readonly = t.hasAttribute("readonly")),
                    (i.placeholder = t.getAttribute("placeholder") || i.placeholder || ""),
                    (i.required = t.hasAttribute("required")),
                    this.isIE && (i.autoComplete = !1),
                    ["whitelist", "blacklist"].forEach(function (e) {
                        var s = t.getAttribute("data-" + e);
                        s && (s = s.split(i.delimiters)) instanceof Array && (i[e] = s);
                    }),
                    "autoComplete" in e && !o(e.autoComplete) && ((i.autoComplete = this.DEFAULTS.autoComplete), (i.autoComplete.enabled = e.autoComplete)),
                    "mix" == i.mode && ((i.autoComplete.rightKey = !0), (i.delimiters = e.delimiters || null)),
                    t.pattern)
                )
                    try {
                        i.pattern = new RegExp(t.pattern);
                    } catch (t) {}
                if (this.settings.delimiters)
                    try {
                        i.delimiters = new RegExp(this.settings.delimiters, "g");
                    } catch (t) {}
                "select" == i.mode && (i.dropdown.enabled = 0), (i.dropdown.appendTarget = e.dropdown && e.dropdown.appendTarget ? e.dropdown.appendTarget : document.body);
            },
```
I did try just replacing the default, and that didn't do anything remarkably different than just setting it in my own settings. I'm still confused about how you are thinking for the javascript to parse the string, and derive the tags from something like `?tags=one,two,three` - here is how it is done without worrying about tags within entities:

```python
function add_tags_by_key(key) {
    var querytags = []

    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    string = urlParams.get(key);
    console.log(string)
    if (string != undefined) {
        $.each(string.split(','), function(i, e) {
            querytags.push({"value": e,  "code": key})
        })
    }
    tagify.addTags(querytags)
}
```
Regardless of whether the `,` is encoded of not, by the time we get there when we console.log we see the string:

E.g., this url `http://127.0.0.1:8000/phenotypes/?phenotype=growth%20(pooled%20culture%2C%20microarray)` results in a string `growth (pooled culture, microarray)` which is then still split by comma.

I don't have vision for what you had in mind for url-encoding to work - but I can suggest other ideas. Possibly using a different delimiter like `|` instead to separate values? Will `|` ever come up in a query? For example, the query `http://127.0.0.1:8000/phenotypes/?phenotype=growth%20(pooled%20culture,%20microarray)`
results in 

![image](https://user-images.githubusercontent.com/814322/100830775-a747d580-3421-11eb-88b4-f069341bd05a.png)

And that means the `all` query looks like `http://127.0.0.1:8000/phenotypes/?tags=morphology|organelle|peroxisome`
And then results as we'd expect:

![image](https://user-images.githubusercontent.com/814322/100831008-145b6b00-3422-11eb-9435-bd77484c7e0f.png)

We could even double it up (`||`) to be extra sure, let me know what you think.

**Comment by abarysh** [comment]
Yeah, having thought a bit more about this, I think that a single pipe ("|") would be a good solution for now. I don't anticipate ever using a pipe within any fields in the database.

**Comment by vsoch** [comment]
Gotcha! I'll get these changes in soon.

**Comment by vsoch** [comment]
Deployed to staging.
