### ISSUE TITLE
Filtering tables is slow

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#78]
Examples: /papers/ and /conditions/ search results.

**Comment by vsoch** [comment]
I’ll give this a shot tomorrow! Hopefully I can at least identify why it’s slow.

**Comment by vsoch** [comment]
I can't reproduce this with papers or conditions - the columns load in a reasonable time. Let's try to find a specific example to reproduce the slowness.

**Comment by abarysh** [comment]
Agree. The filtering is not immediate, but it works well. Closing the issue.
