### ISSUE TITLE
Make sure autocomplete are unique (no redundant entries)

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#83]
E.g., typing in "vulpe" in papers explorer gives several identical suggestions.

**Comment by vsoch** [comment]
okay just looked into this - the issue was that we were creating a list of all authors by combining first and last authors, and although distinct was done separately on each query, we needed to then find the unique within that set. The only other place this might apply is for gene names, but if there isn't overlap between gene systametic, common, etc. names, we shouldn't need to add the additional parsing there.

**Comment by abarysh** [comment]
I wouldn't expect to be much overlap between first and last author names (e.g., I think "vulpe" is only a last name in our DB). When I glanced at this, I thought it was because `distinct()` had to be done before `value_list()`, not after. But I agree with you, to be perfectly consistent, we need to merge first authors and last authors and then take the unique set of those.

I haven't noticed a similar problem with gene names. There is probably a handful of isolated examples of overlap between common names and aliases. If it's easy to address, we might as well do it now. If not, gene names can wait.

**Comment by vsoch** [comment]
Good thinking - distinct() should come first, I'll do that too!

**Comment by abarysh** [comment]
In PR #81 -- /phenotypes/ still have some redundancy between autocomplete suggestions. E.g., "autophagy" -- I see 3 identical suggestions instead of 1.

**Comment by vsoch** [comment]
Hmm, it must be that there are shared tags between attributes. The tags map to specific queries, but in the case of different tag types (showing up as the same thing here) we can’t tell them apart. What if we remove the custom tags all together, get a list of unique things, and treat them all as generic query strings?

**Comment by abarysh** [comment]
Agree! I think that's the way to go.

**Comment by vsoch** [comment]
Awesome! I should have time to do this tomorrow, need to have dinner :)

**Comment by abarysh** [comment]
Having checked this on /papers/ I now realized I misunderstood what you meant. I thought we were going to merge all the tags for a specific module, not all tags for all modules. E.g., as I start typing "br" in /papers/ I see lots of gene names that match "br", but it doesn't make much sense to look for gene names in /papers/ and we shouldn't suggest them in autocomplete. Would it help if I made a list of fields/tags that should be included in autocomplete for each explorer?

**Comment by vsoch** [comment]
You were correct about what I originally meant - it's a specific set of tags per explorer. It shouldn't be the case that we have gene names for papers, it was just an oversight adding it here, and should be easy to remove. https://github.com/yeastphenome/yeastphenome.org/blob/master/yeastphenome/apps/papers/search.py#L21.

**Comment by vsoch** [comment]
If you want to review, each set of tags is in the top function of the search.py for each module. They are all different!

**Comment by abarysh** [comment]
Cool! I'll have a look!

**Comment by abarysh** [comment]
Should be all addressed in PR #91
