### ISSUE TITLE
Filtering of conditions results table doesn’t work

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#85]
Example: at /conditions/ search for "expression" and try to filter by "size"

**Comment by vsoch** [comment]
okay this came down to having two query expressions (e.g., "expression" from the search box and "size" as a filter - they both go in as query parameters, and the query parameters were being done as a regular expression with OR. This is now fixed (and we will need to do this for other views that support multiple queries) but what still doesn't work is to filter by the extra fields like doses and phenotype list. I tried adding the annotation of each to the search function and then query over it, but it was way too slow to be functional. So right now the filter will work for only simple attributes.

**Comment by abarysh** [comment]
Just as food for thought -- at the beginning, these tables were filtered in the browser, rather than on the server side, right? My understanding is that, in that case, filtering would work with whatever is in the table, no matter how it was generated. Could it be a good idea to reconsider that implementation? We moved away from it because of some large querysets. Do you remember what was the problem exactly?

**Comment by vsoch** [comment]
We definitely can no longer handle any kind of filtering in the browser!

So for the server side rendering, the request is run both on the page load (when there aren't rows) and then for any change to the table (filter or sort). The default data sent doesn't include anything about the original data columns, e.g.,

```
<QueryDict: {'query': ['expression'], 'draw': ['4'], 'columns[0][data]': ['0'], 'columns[0][name]': [''], 'columns[0][searchable]': ['true'], 'columns[0][orderable]': ['true'], 'columns[0][search][value]': [''], 'columns[0][search][regex]': ['false'], 'columns[1][data]': ['1'], 'columns[1][name]': [''], 'columns[1][searchable]': ['true'], 'columns[1][orderable]': ['true'], 'columns[1][search][value]': [''], 'columns[1][search][regex]': ['false'], 'columns[2][data]': ['2'], 'columns[2][name]': [''], 'columns[2][searchable]': ['true'], 'columns[2][orderable]': ['true'], 'columns[2][search][value]': [''], 'columns[2][search][regex]': ['false'], 'columns[3][data]': ['3'], 'columns[3][name]': [''], 'columns[3][searchable]': ['true'], 'columns[3][orderable]': ['true'], 'columns[3][search][value]': [''], 'columns[3][search][regex]': ['false'], 'columns[4][data]': ['4'], 'columns[4][name]': [''], 'columns[4][searchable]': ['true'], 'columns[4][orderable]': ['true'], 'columns[4][search][value]': [''], 'columns[4][search][regex]': ['false'], 'order[0][column]': ['0'], 'order[0][dir]': ['asc'], 'start': ['0'], 'length': ['10'], 'search[value]': ['human'], 'search[regex]': ['false'], '_': ['1607648251203']}>
```
(sorry it's a bit hard to read, but you see they aren't there).

But what I think we can try is to send an additional attribute of the serialized ids of the current selection, and then given this exists, skip the long query all together and just filter that down. To do this I could accept another argument to the conditions_search function to be some custom queryset (and skip getting all the condition types).

**Comment by abarysh** [comment]
I guess my thinking is this: if filtering effectively runs another query (just like adding another term to the search box), why don't we just get rid of it? Users will just add additional search criteria to the search box and the effect (and the loading time) will be the same. Am I misunderstanding it?

**Comment by vsoch** [comment]
oh that would be much easier to implement! And it makes sense.

**Comment by abarysh** [comment]
I tried adding multiple criteria to the search in /papers/, but the behavior is not quite as expected. Example:

- Search for "Brown GW" -> got 4 papers (correct)
- Added "MMS" to the search box -> the "MMS" tag does not appear in the search box and the results are now 18 papers (I'm guessing, it's an OR not an AND search?). The query string in the URL is `/?query=Brown%20GW&query=MMS`, which I guess means that the first criterium "Brown GW" is ignored.
- If I add "MMS [0.001%]" to the search (from autocomplete), the query string is `/?query=Brown%20GW|MMS%20[0.001%]`, but the results still indicate that the first criterium "Brown GW" is ignored.

**Comment by vsoch** [comment]
It should parse to `?query=Brown W|MMS`, so we just need to fix to be that. Let me take a look!

**Comment by abarysh** [comment]
See my edit above -- it does ad `|MMS ...` to the query when you search matches an autocomplete option, but the result is still the same.

**Comment by vsoch** [comment]
There are two separate bugs, one for having the double query parameter, and the second for something about the search.

**Comment by abarysh** [comment]
Yeah, sounds good, take your time to figure this out. Let's make sure it's implemented as simply as possible. That will make it less likely to break later on.

**Comment by vsoch** [comment]
okay, fixed it (and need to do the same for the other views). The issue wasn't on the backend search, but the looping through queries to generate the request. The logic needed to change now that we have a flattened list of general words to use as queries. I was able to do the three steps you outlined above to go from 4, to 2, and then to 1, but for the last term it needed to be MMS 0.035%.

**Comment by abarysh** [comment]
Cool! Yeah, check out the other explorer pages. All of them seem to have a similar issue with the multiple parameter search. Some of them (e.g., conditions) also seem to have the double query in the URL issue.

**Comment by vsoch** [comment]
okay these fixes are deployed to staging, if you want to take a look. I'm going to look at the genes scores issue now.

**Comment by abarysh** [comment]
Fixes work great. Tested every explorer page with multiple options. Everything behaves as expected.

**Comment by vsoch** [comment]
Still works!
