### ISSUE TITLE
rename ganes tables to be under genes module

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#86]
Right now, genes is nested inside datasets, and should be moved into it's own module. The meta attribute for the database prefix should not be changed so the table is not dropped.

**Comment by vsoch** [comment]
I was excited about this and started work tonight, should be able to get in a PR this weekend! I'm doing it very carefully because I absolutely don't want to do something wrong with a migration moving genes into it's own module.

**Comment by abarysh** [comment]
Sounds good! Yes, let's not do any migrations for this change. It's too delicate. It's a very easy change on the database side, we can do it manually in 5 min when we are ready.

**Comment by vsoch** [comment]
I definitely won't! I'll open the PR with the changes for you to take a look first.

**Comment by vsoch** [comment]
Also note that we can set `db_table` in Meta and not need to rename the table -> https://realpython.com/move-django-model/#the-short-way-reference-the-new-django-model-to-the-old-table

**Comment by abarysh** [comment]
Yeah, true, but django's conventions for naming tables (<app>_<model>) are so good and so clear that you kinda want to keep it. All we'll need to do is to rename `datasets_gene` to `genes_gene` etc.

**Comment by vsoch** [comment]
okay, then that's what we'll do :)

**Comment by vsoch** [comment]
Okay working on this now - should get the PR in this morning! It's enough changes that let's try to get this in next before making other fixes.

**Comment by vsoch** [comment]
This has been merged! I'm going to rename to be about renaming the table.

**Comment by vsoch** [comment]
That's weird, we can only do one assignee! We are both assigned to this.

**Comment by vsoch** [comment]
We should also make name for `GeneAlias` a non null field, see https://github.com/yeastphenome/yeastphenome.org/pull/121#pullrequestreview-555915575

**Comment by vsoch** [comment]
Done with #123
