### ISSUE TITLE
Issues for after first release

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#89]
These issues I can move into separate issues, but for now will just add a list here.

- [ ]  SAFE plots 
- [ ]  table of similarities - add column to table with link to scatterplot for that similarity.
- [ ]  remove search box for gene search in plot.html, clicking on bar should be able to find gene and bar is highlighted and row is too.
- [ ]  schema.org embed data for dataset search
- [ ]  custom 404 page
- [ ]  data refactoring - review gene table (should have SGD list)
- [ ]  should Gene be included in admin views (yes) e.g., mutants are found to have problems
- [ ]  brand new section - tools!

**Comment by abarysh** [comment]
I added the most critical of these as separate issues. So closing this one, it's all covered!
