### ISSUE TITLE
Pages missing datasets warning

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#92]
@abarysh do we want to put the warning anywhere there are datasets, or anywhere there is a download button? We have a few pages with dataset tables that might need the warning added:

 - /conditions/9787/ has a table of associated datasets, so should have the warning above it
 - /papers/216/ also has a table of datasets
 - /phenotypes/591/
 - datasets explorer

If it's just for download pages, feel free to close this issue!

**Comment by abarysh** [comment]
I agree with you, let's add the warning anywhere there's a download button. It won't hurt and it's easy to remove.

**Comment by vsoch** [comment]
Sorry I think I wasn't specific - right now I *do*think we have them everywhere with download buttons (unless I missed one!) I was suggesting that we have it anywhere there is a data table, because there is an "Add to cart." but if the user adds to the cart, they will definitely see the message when they download there. So I think adding to all tables might be overkill?

**Comment by abarysh** [comment]
Yeah, I agree. I think it's ok to have the warning whenever the user actually downloads things: 

1) Nearby the buttons that download immediately
2) In the Cart

If we already have this, feel free to close the issue.

**Comment by vsoch** [comment]
Yep, we're good (just checked again, we have for each of genes/datasets similar and scores tables, and the linked "View All" views.
