### ISSUE TITLE
Provide immediate feedback to user on adding to cart

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#95]
Currently, for views that retrieve data with ajax (and don't refresh the page) we miss out on Django messages, and wind up with https://github.com/yeastphenome/yeastphenome.org/issues/76#issuecomment-743783115. We should have some strategy to be able to send back a message that can be used to update the page, even without reload.

**Comment by abarysh** [comment]
Related to this: after adding exactly 50 datasets (from, e.g., /papers/289/), I checked the Download Cart and saw 3 messages warning me that I exceeded the quota of 50 (although the message still has a typo and says 500). The Cart was empty before I started adding datasets.

**Comment by vsoch** [comment]
Yeah that happens because the message is added to the request, and it only appears the next time you refresh a view and see any messages. There must be another 500 hard coded somewhere (although right now I cannot find it).

**Comment by vsoch** [comment]
I'm not able to reproduce this - I think likely it resulted from some previously existing "Add all to cart" button which is now removed from that page? Looking at the code, the function does have a check for if it's a POST, and in the case of a POST doesn't add a message to the request. So for now let's keep the issue open and look for it to happen again.

**Comment by vsoch** [comment]
@abarysh is this still an issue? I think we can close it in favor of the refactor described in #128 - if we have a single button that makes changes to a bunch of selected datasets at once (with a server refresh) we can easily reload the page and show a message.

**Comment by abarysh** [comment]
I guess this is now related to our discussion in #102 . But currently the messaging is out of place -- when you reach the Cart's limit, you get the blue info box ("You are limited to adding no more than 50 datasets to your Download Cart") at the very top of the page that you don't see (I had to scroll back up to see the message and I'm working on a large screen; a laptop screen will be even more problematic). The box should probably be an alert (red), appear below "Datasets" but above the table, and be temporary (disappear after some time, I think bootstrap provides that option).

**Comment by vsoch** [comment]
Okay, so you'd like a special messages spot (separate from the default that we use for messages attached to a request) to appear at the bottom of the datasets title, above the table?

**Comment by vsoch** [comment]
This is fixed, will deploy to staging soon!

**Comment by abarysh** [comment]
>Okay, so you'd like a special messages spot (separate from the default that we use for messages attached to a request) to appear at the bottom of the datasets title, above the table?

Yes, the message has to be visible. If it's outside of the user's field of view, it's not going to be useful.
