### ISSUE TITLE
Enforce https for staging and production

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#99]
We should be able to just check that it's running on app engine, and then set the correct variable in settings.py

```python
# If we are on app engine, ensure https only
if os.getenv("RUNNING_APP_ENGINE") == "yes":
    SECURE_SSL_REDIRECT = True
```

**Comment by vsoch** [comment]
okay going to add this to the next round of changes, so we should be able to test on staging first.

**Comment by abarysh** [comment]
Tested on staging -- fixed
